"""initial schema

Revision ID: 91b0ee0279d4
Revises: 
Create Date: 2025-12-24 13:57:14.486887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91b0ee0279d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_checkpoints',
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source_name')
    )
    op.create_table('etl_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('normalized_crypto_assets',
    sa.Column('asset_uid', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_usd', sa.Numeric(), nullable=True),
    sa.Column('market_cap_usd', sa.Numeric(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('asset_uid')
    )
    op.create_index(op.f('ix_normalized_crypto_assets_asset_uid'), 'normalized_crypto_assets', ['asset_uid'], unique=False)
    op.create_index(op.f('ix_normalized_crypto_assets_symbol'), 'normalized_crypto_assets', ['symbol'], unique=False)
    op.create_table('raw_coingecko',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_coinpaprika',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_coinpaprika')
    op.drop_table('raw_coingecko')
    op.drop_index(op.f('ix_normalized_crypto_assets_symbol'), table_name='normalized_crypto_assets')
    op.drop_index(op.f('ix_normalized_crypto_assets_asset_uid'), table_name='normalized_crypto_assets')
    op.drop_table('normalized_crypto_assets')
    op.drop_table('etl_runs')
    op.drop_table('etl_checkpoints')
    # ### end Alembic commands ###
